### ISSUE TITLE
Error when training Yolo Network

### ISSUE THREAD

**Issue by mylastai** [supervisely-ecosystem/yolov5#49]
I am using Train YOLOv5 App in supervisely to detect objects in RGB images.

Following error message occurs when I start the training:

```
Oops! Something went wrong, please try again or contact tech support. Find more info in the app logs. Error: AttributeError("Can't get attribute 'SPPF' on <module 'models.common' from '/sessions/344196/repo/models/common.py'>")

stack=[
  Traceback (most recent call last):
    File "/sessions/344196/repo/supervisely/train/src/sly_train.py", line 71, in train
      train_yolov5.main()
    File "/sessions/344196/repo/train.py", line 598, in main
      train(hyp, opt, device, tb_writer)
    File "/sessions/344196/repo/train.py", line 97, in train
      ckpt = torch.load(weights, map_location=device)  # load checkpoint
    File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 594, in load
      return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 853, in _load
      result = unpickler.load()
  AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/sessions/344196/repo/models/common.py'>
]
```
I use the "latest" version of the App. 

I leave all parameters at default as they come when you load the App fresh.

I have one class selected for detection (need a licence plate detector).

Please advice what to do.  

As I understand from this page (Link)[https://githubmemory.com/repo/ultralytics/yolov5/issues/5143] this error might have something to do with loading a pre-learnt model in a specific version of Pytorch.

**Comment by gembancud** [comment]
Hello, Im currently experiencing the same problem. I believe this issue stems from the fact that the yolov5 fork referred by supervisely is of release v5 while the actual ultralytics/yolov5 is on release v6. Using the already pretrained weights will work. for custom weights it won't since it adds the SPPF model to make computations faster. My suggestion would be checking out to releasev5 and retraining your weights from there. I'll be doing it likewise so if you don't hear from me, then It probably is the correct solution.

**Comment by gembancud** [comment]
On the other hand you dont have to checkout the previous release commit. You can simply download the model you need from the [Releases page](https://github.com/ultralytics/yolov5/releases/tag/v5.0). You can still train it on the master branch
